/* Autogenerated by hxtools bin2c */
#ifndef SHRED_DB_H
#define SHRED_DB_H 1

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char bin2c_shred_db_jpg[11560];

#ifdef __cplusplus
} /* extern "C" */
#endif


#endif /* SHRED_DB_H */
